name: bundle-release-gds-way

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: add-cloudfoundry-repository
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

      - name: install-node
        uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: npm
          cache-dependency-path: |
            Gemfile
            Gemfile.lock

      - name: install-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundle-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: install-cloudfoundry-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y cf7-cli

      - name: bundle-gds-way
        run: |
          bundle exec middleman build

      - name: deploy-to-paas
        env:
          CF_USERNAME: ${{ secrets.CF_EMAIL }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: | 
          cf api https://api.cloud.service.gov.uk 
          cf auth
          cf target -o gds-tech-ops -s docs

          cf push -f ./manifest.yml
